spring:
  application:
  name: CouponService
  
    
config: 
    import:
        -optional:configserver:http://localhost:8888
        
       
server: 
  port: 7070
eureka:
  client:
  fetch-registry: true
  register-with-eureka: true
  
service-url:
      defaultZone: http://localhost:8761/eureka
        
         
instance:
 hostname: localhost

