server:
  port: 8888
spring:
 
  cloud:
    config:
      server:
        git:
          uri: D:\Microservicelocalrepository
                    
eureka:
  client: 
  fetch-registry: true
  register-with-eureka: true
  service-url:
    defaultZone: http://localhost:8761/eureka
instance:
  hostname: localhost