eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      instance:
        hostname: localhost
      
      zipkin: 
          base-url: http://127.0.0.1:9411/
server:
  port: 8765
spring:
  application:
    name: gateway-service
    cloud: 
      routes:
       -id: couponService
       uri: lb://COUPON-SERVICE
       predicates: path=/coupons/**
       
       -id: productService
       uri: lb://PRODUCT-SERVICE
       predicates: path=/products/**
   